//
//  PlacesKit.h
//  Places@SST
//
//  Created by Pan Ziyue on 2/1/15.
//  Copyright (c) 2015 StatiX Industries. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PlacesKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* fullTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* halfTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* noneTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* lowTargets;

// Generated Images
+ (UIImage*)imageOfFull;
+ (UIImage*)imageOfHalf;
+ (UIImage*)imageOfNone;
+ (UIImage*)imageOfLow;

@end
